import { Vehicle } from "../models/vehicle.model";
import { getCurrentYear } from "../utils/strings";

export const emptyVehicleObj: Vehicle = {
    id: '',
    plateNumber: '',
    make: '',
    model: '',
    manufactureYear: getCurrentYear(),
    vinNumber: '',
    engineHorsePower: 150,
    engineCapacityCC: 2000,
    fuelType: '',
    expirationDateITP: 0,
    expirationDateRCA: 0,
  };

  export const MakeIconClassName: { make: string, iconClassName: string }[] = [
    { make: 'Acura', iconClassName: 'car-acura' },
    { make: 'Alfa Romeo', iconClassName: 'car-alfa-romeo' },
    { make: 'Alfa Romeo Alt', iconClassName: 'car-alfa-romeo-alt' },
    { make: 'AM General', iconClassName: 'car-am-general' },
    { make: 'Aston Martin', iconClassName: 'car-aston-martin' },
    { make: 'Aston Martin Alt', iconClassName: 'car-aston-martin-alt' },
    { make: 'Audi', iconClassName: 'car-audi' },
    { make: 'Bentley', iconClassName: 'car-bentley' },
    { make: 'BMW', iconClassName: 'car-bmw' },
    { make: 'Bugatti', iconClassName: 'car-bugatti' },
    { make: 'Buick', iconClassName: 'car-buick' },
    { make: 'Cadillac', iconClassName: 'car-cadillac' },
    { make: 'Chevrolet', iconClassName: 'car-chevrolet' },
    { make: 'Chrysler', iconClassName: 'car-chrysler' },
    { make: 'Citroen', iconClassName: 'car-citroen' },
    { make: 'Dacia', iconClassName: 'car-dacia' },
    { make: 'Daewoo', iconClassName: 'car-daewoo' },
    { make: 'Default', iconClassName: 'car-default' },
    { make: 'Dodge', iconClassName: 'car-dodge' },
    { make: 'Eagle', iconClassName: 'car-eagle' },
    { make: 'Ferrari', iconClassName: 'car-ferrari' },
    { make: 'Fiat', iconClassName: 'car-fiat' },
    { make: 'Fiat Alt', iconClassName: 'car-fiat-alt' },
    { make: 'Fisker', iconClassName: 'car-fisker' },
    { make: 'Ford', iconClassName: 'car-ford' },
    { make: 'Genesis', iconClassName: 'car-genesis' },
    { make: 'Geo', iconClassName: 'car-geo' },
    { make: 'GMC', iconClassName: 'car-gmc' },
    { make: 'Honda', iconClassName: 'car-honda' },
    { make: 'Hummer', iconClassName: 'car-hummer' },
    { make: 'Hyundai', iconClassName: 'car-hyundai' },
    { make: 'Infiniti', iconClassName: 'car-infiniti' },
    { make: 'Isuzu', iconClassName: 'car-isuzu' },
    { make: 'Jaguar', iconClassName: 'car-jaguar' },
    { make: 'Jaguar Alt', iconClassName: 'car-jaguar-alt' },
    { make: 'Jeep', iconClassName: 'car-jeep' },
    { make: 'Jeep Alt', iconClassName: 'car-jeep-alt' },
    { make: 'Kia', iconClassName: 'car-kia' },
    { make: 'Lamborghini', iconClassName: 'car-lamborghini' },
    { make: 'Lamborghini Alt', iconClassName: 'car-lamborghini-alt' },
    { make: 'Land Rover', iconClassName: 'car-land-rover' },
    { make: 'Lexus', iconClassName: 'car-lexus' },
    { make: 'Lincoln', iconClassName: 'car-lincoln' },
    { make: 'Lotus', iconClassName: 'car-lotus' },
    { make: 'Lotus Alt', iconClassName: 'car-lotus-alt' },
    { make: 'Maserati', iconClassName: 'car-maserati' },
    { make: 'Maybach', iconClassName: 'car-maybach' },
    { make: 'Mazda', iconClassName: 'car-mazda' },
    { make: 'Mazda Alt', iconClassName: 'car-mazda-alt' },
    { make: 'McLaren', iconClassName: 'car-mclaren' },
    { make: 'McLaren Alt', iconClassName: 'car-mclaren-alt' },
    { make: 'Mercedes-Benz', iconClassName: 'car-mercedes-benz' },
    { make: 'Mercedes-Benz Alt', iconClassName: 'car-mercedes-benz-alt' },
    { make: 'Mercury', iconClassName: 'car-mercury' },
    { make: 'Mini', iconClassName: 'car-mini' },
    { make: 'Mini Alt', iconClassName: 'car-mini-alt' },
    { make: 'Mitsubishi', iconClassName: 'car-mitsubishi' },
    { make: 'Nissan', iconClassName: 'car-nissan' },
    { make: 'Oldsmobile', iconClassName: 'car-oldsmobile' },
    { make: 'Opel', iconClassName: 'car-opel' },
    { make: 'Panoz', iconClassName: 'car-panoz' },
    { make: 'Peugeot', iconClassName: 'car-peugeot' },
    { make: 'Peugeot Alt', iconClassName: 'car-peugeot-alt' },
    { make: 'Plymouth', iconClassName: 'car-plymouth' },
    { make: 'Pontiac', iconClassName: 'car-pontiac' },
    { make: 'Porsche', iconClassName: 'car-porsche' },
    { make: 'Ram', iconClassName: 'car-ram' },
    { make: 'Ram Alt', iconClassName: 'car-ram-alt' },
    { make: 'Renault', iconClassName: 'car-renault' },
    { make: 'Renault Alt', iconClassName: 'car-renault-alt' },
    { make: 'Rolls-Royce', iconClassName: 'car-rolls-royce' },
    { make: 'Saab', iconClassName: 'car-saab' },
    { make: 'Saab Alt', iconClassName: 'car-saab-alt' },
    { make: 'Saturn', iconClassName: 'car-saturn' },
    { make: 'Scion', iconClassName: 'car-scion' },
    { make: 'Seat', iconClassName: 'car-seat' },
    { make: 'Skoda', iconClassName: 'car-skoda' },
    { make: 'Smart', iconClassName: 'car-smart' },
    { make: 'Spyker', iconClassName: 'car-spyker' },
    { make: 'Spyker Alt', iconClassName: 'car-spyker-alt' },
    { make: 'Subaru', iconClassName: 'car-subaru' },
    { make: 'Subaru Alt', iconClassName: 'car-subaru-alt' },
    { make: 'Suzuki', iconClassName: 'car-suzuki' },
    { make: 'Tesla', iconClassName: 'car-tesla' },
    { make: 'Toyota', iconClassName: 'car-toyota' },
    { make: 'Volkswagen', iconClassName: 'car-volkswagen' },
    { make: 'Volvo', iconClassName: 'car-volvo' },
    { make: 'Volvo Alt', iconClassName: 'car-volvo-alt' },
    { make: 'Aston Martin', iconClassName: 'car-aston-martin' },
    { make: 'Tesla', iconClassName: 'car-tesla' },
    { make: 'Jaguar', iconClassName: 'car-jaguar' },
    { make: 'Maserati', iconClassName: 'car-maserati' },
    { make: 'Rolls-Royce', iconClassName: 'car-rolls-royce' },
    { make: 'Toyota', iconClassName: 'car-toyota' },
    { make: 'Mercedes-Benz', iconClassName: 'car-mercedes-benz' },
    { make: 'BMW', iconClassName: 'car-bmw' },
    { make: 'Bugatti', iconClassName: 'car-bugatti' },
    { make: 'Mini', iconClassName: 'car-mini' },
    { make: 'Ford', iconClassName: 'car-ford' },
    { make: 'Lincoln', iconClassName: 'car-lincoln' },
    { make: 'Mercury', iconClassName: 'car-mercury' },
    { make: 'Lotus', iconClassName: 'car-lotus' },
    { make: 'Chevrolet', iconClassName: 'car-chevrolet' },
    { make: 'Buick', iconClassName: 'car-buick' },
    { make: 'Cadillac', iconClassName: 'car-cadillac' },
    { make: 'Holden', iconClassName: 'car-default' },
    { make: 'Opel', iconClassName: 'car-opel' },
    { make: 'GMC', iconClassName: 'car-gmc' },
    { make: 'Mazda', iconClassName: 'car-mazda' },
    { make: 'Honda', iconClassName: 'car-honda' },
    { make: 'Acura', iconClassName: 'car-acura' },
    { make: 'Nissan', iconClassName: 'car-nissan' },
    { make: 'Mitsubishi', iconClassName: 'car-mitsubishi' },
    { make: 'Subaru', iconClassName: 'car-subaru' },
    { make: 'Suzuki', iconClassName: 'car-suzuki' },
    { make: 'Toyota', iconClassName: 'car-toyota' },
    { make: 'Lexus', iconClassName: 'car-lexus' },
    { make: 'Infiniti', iconClassName: 'car-infiniti' },
    { make: 'Hyundai', iconClassName: 'car-hyundai' },
    { make: 'Kia', iconClassName: 'car-kia' },
    { make: 'Genesis', iconClassName: 'car-genesis' },
    { make: 'Honda', iconClassName: 'car-honda' },
    { make: 'Lexus', iconClassName: 'car-lexus' },
    { make: 'Infiniti', iconClassName: 'car-infiniti' },
    { make: 'Kia', iconClassName: 'car-kia' },
    { make: 'Audi', iconClassName: 'car-audi' },
    { make: 'Mercedes-Benz', iconClassName: 'car-mercedes-benz' },
    { make: 'BMW', iconClassName: 'car-bmw' },
    { make: 'Porsche', iconClassName: 'car-porsche' },
    { make: 'Volvo', iconClassName: 'car-volvo' },
    { make: 'Volkswagen', iconClassName: 'car-volkswagen' },
    { make: 'Jaguar', iconClassName: 'car-jaguar' },
    { make: 'Land Rover', iconClassName: 'car-land-rover' },
    { make: 'Range Rover', iconClassName: 'car-default' },
    { make: 'Bentley', iconClassName: 'car-bentley' },
    { make: 'Jaguar', iconClassName: 'car-jaguar' },
    { make: 'Land Rover', iconClassName: 'car-land-rover' },
    { make: 'Aston Martin', iconClassName: 'car-aston-martin' },
    { make: 'Land Rover', iconClassName: 'car-land-rover' },
    { make: 'Rolls-Royce', iconClassName: 'car-rolls-royce' },
    { make: 'Lotus', iconClassName: 'car-lotus' },
    { make: 'Porsche', iconClassName: 'car-porsche' },
    { make: 'Lamborghini', iconClassName: 'car-lamborghini' },
    { make: 'McLaren', iconClassName: 'car-mclaren' },
    { make: 'Bugatti', iconClassName: 'car-bugatti' },
    { make: 'Koenigsegg', iconClassName: 'car-koenigsegg' },
    { make: 'Ferrari', iconClassName: 'car-ferrari' },
    { make: 'Pagani', iconClassName: 'car-default' },
    { make: 'Maserati', iconClassName: 'car-maserati' },
    { make: 'Alfa Romeo', iconClassName: 'car-alfa-romeo' },
    { make: 'Fiat', iconClassName: 'car-fiat' },
    { make: 'Lancia', iconClassName: 'car-default' },
    { make: 'Tesla', iconClassName: 'car-tesla' },
    { make: 'Rivian', iconClassName: 'car-default' },
    { make: 'Bollinger', iconClassName: 'car-default' },
    { make: 'Rivian', iconClassName: 'car-default' },
    { make: 'Hennessey', iconClassName: 'car-default' },
    { make: 'Lucid', iconClassName: 'car-default' },
    { make: 'Mullen', iconClassName: 'car-default' },
    { make: 'Fisker', iconClassName: 'car-fisker' },
    { make: 'Nikola', iconClassName: 'car-default' },
    { make: 'Lordstown', iconClassName: 'car-default' },
    { make: 'Lordstown', iconClassName: 'car-default' },
    { make: 'Alpha', iconClassName: 'car-default' },
    { make: 'Alpha', iconClassName: 'car-default' },
    { make: 'Detroit Electric', iconClassName: 'car-default' },
    { make: 'Detroit Electric', iconClassName: 'car-default' },
    { make: 'Electric Mobility Company', iconClassName: 'car-default' },
    { make: 'Lucid Motors', iconClassName: 'car-default' },
    { make: 'Fisker Automotive', iconClassName: 'car-default' },
    { make: 'Electra Meccanica', iconClassName: 'car-default' },
    { make: 'Aptera Motors', iconClassName: 'car-default' },
    { make: 'Electrameccanica', iconClassName: 'car-default' },
    { make: 'Mercury', iconClassName: 'car-mercury' },
    { make: 'Holden', iconClassName: 'car-default' },
    { make: 'Rezvani', iconClassName: 'car-default' },
    { make: 'NIO', iconClassName: 'car-default' },
    { make: 'Faraday Future', iconClassName: 'car-default' },
    { make: 'Lancia', iconClassName: 'car-default' },
    { make: 'Maserati', iconClassName: 'car-maserati' },
    { make: 'BYD', iconClassName: 'car-default' },
    { make: 'Wheego Electric Cars', iconClassName: 'car-default' },
    { make: 'Mercedes-Benz', iconClassName: 'car-mercedes-benz' },
    { make: 'Safari Cars Ltd.', iconClassName: 'car-default' },
    { make: 'Elio Motors', iconClassName: 'car-default' },
    { make: 'Smith Electric Vehicles', iconClassName: 'car-default' },
    { make: 'Aurica Motors LLC', iconClassName: 'car-default' },
    { make: 'Plymouth', iconClassName: 'car-plymouth' },
    { make: 'Jaguar', iconClassName: 'car-jaguar' },
    { make: 'Bricklin', iconClassName: 'car-default' },
    { make: 'Lifan', iconClassName: 'car-default' },
    { make: 'Kandi', iconClassName: 'car-kandi' },
    { make: 'Koenigsegg', iconClassName: 'car-koenigsegg' },
    { make: 'Tesla', iconClassName: 'car-tesla' },
    { make: 'Electric Mobile Cars', iconClassName: 'car-default' },
    { make: 'Avera Motors', iconClassName: 'car-default' },
    { make: 'Bakkura Mobility', iconClassName: 'car-default' },
    { make: 'Th!nk', iconClassName: 'car-default' },
    { make: 'Coda', iconClassName: 'car-default' },
    { make: 'Contemporary Classic Cars (CCC)', iconClassName: 'car-default' },
    { make: 'Byd', iconClassName: 'car-default' },
    { make: 'Kandi', iconClassName: 'car-kandi' },
    { make: 'Kepler Motors', iconClassName: 'car-default' },
    { make: 'Making You Mobile', iconClassName: 'car-default' },
    { make: 'MyCar', iconClassName: 'car-default' },
    { make: 'NJD Automotive LLC', iconClassName: 'car-default' },
    { make: 'Phoenix Motorcars', iconClassName: 'car-default' },
    { make: 'Rocket Sled Motors', iconClassName: 'car-default' },
    { make: 'Vision Industries', iconClassName: 'car-default' },
    { make: 'Warhawk Performance', iconClassName: 'car-default' },
    { make: 'Ukeycheyma', iconClassName: 'car-default' },
    { make: 'Total Electric Vehicles', iconClassName: 'car-default' },
    { make: 'Spyker', iconClassName: 'car-spyker' },
    { make: 'Oldsmobile', iconClassName: 'car-oldsmobile' },
    { make: 'Panoz', iconClassName: 'car-panoz' },
    { make: 'Saleen', iconClassName: 'car-default' },
    { make: 'Solectria', iconClassName: 'car-default' },
    { make: 'Yester Year Auto', iconClassName: 'car-default' },
    { make: 'BXR', iconClassName: 'car-default' },
    { make: 'Engine Connection', iconClassName: 'car-default' },
    { make: 'Bluecar', iconClassName: 'car-default' },
    { make: 'Mosler', iconClassName: 'car-default' },
    { make: 'Pagani', iconClassName: 'car-default' },
    { make: 'Revology', iconClassName: 'car-default' },
    { make: 'EMA', iconClassName: 'car-default' },
    { make: 'Costin Sports Car', iconClassName: 'car-default' },
    { make: 'Genesis', iconClassName: 'car-genesis' },
    { make: 'CarParts', iconClassName: 'car-default' },
    { make: 'Automobili Lamborghini', iconClassName: 'car-lamborghini' },
    { make: 'The Electric Car Company (ECC)', iconClassName: 'car-default' },
    { make: 'Vanderhall Motor Works', iconClassName: 'car-default' },
    { make: 'DeLorean Motor Company', iconClassName: 'car-default' },
    { make: 'Camal Ltd.', iconClassName: 'car-default' },
    { make: 'Proton', iconClassName: 'car-default' },
    { make: 'Changfeng', iconClassName: 'car-default' },
    { make: 'Hongqi', iconClassName: 'car-default' },
    { make: 'Baojun', iconClassName: 'car-default' },
    { make: 'Jinbei', iconClassName: 'car-default' },
    { make: 'Trumpchi', iconClassName: 'car-default' },
    { make: 'Leopaard', iconClassName: 'car-default' },
    { make: 'Lark', iconClassName: 'car-default' },
    { make: 'Hanteng', iconClassName: 'car-default' },
    { make: 'Denza', iconClassName: 'car-default' },
    { make: 'Chery', iconClassName: 'car-default' },
    { make: 'Polestar', iconClassName: 'car-default' },
    { make: 'Wey', iconClassName: 'car-default' },
    { make: 'Xpeng', iconClassName: 'car-default' },
    { make: 'Morgan', iconClassName: 'car-default' },
    { make: 'Cupra', iconClassName: 'car-default' },
    { make: 'VinFast', iconClassName: 'car-default' },
    { make: 'BRABUS', iconClassName: 'car-default' },
    { make: 'Dartz', iconClassName: 'car-default' },
    { make: 'Rimac', iconClassName: 'car-default' },
    { make: 'Ram', iconClassName: 'car-ram' },
    { make: 'Bristol', iconClassName: 'car-default' },
    { make: 'Noble', iconClassName: 'car-default' },
    { make: 'Hennessey', iconClassName: 'car-default' },
    { make: 'Marussia', iconClassName: 'car-default' },
    { make: 'Brilliance', iconClassName: 'car-default' },
    { make: 'Haval', iconClassName: 'car-default' },
    { make: 'Hawtai', iconClassName: 'car-default' },
    { make: 'WEY', iconClassName: 'car-default' },
    { make: 'SsangYong', iconClassName: 'car-default' },
    { make: 'UAZ', iconClassName: 'car-default' },
    { make: 'Lada', iconClassName: 'car-default' },
    { make: 'GAZ', iconClassName: 'car-default' },
    { make: 'ZAZ', iconClassName: 'car-default' },
    { make: 'PAZ', iconClassName: 'car-default' },
    { make: 'Kamaz', iconClassName: 'car-default' },
    { make: 'MAZ', iconClassName: 'car-default' },
    { make: 'ZIL', iconClassName: 'car-default' },
    { make: 'AZLK', iconClassName: 'car-default' },
    { make: 'Izh', iconClassName: 'car-default' },
    { make: 'TagAZ', iconClassName: 'car-default' },
    { make: 'Renault Samsung Motors', iconClassName: 'car-renault' },
    { make: 'Renault Samsung Motors', iconClassName: 'car-renault' },
    { make: 'Moskvitch', iconClassName: 'car-default' },
    { make: 'Volga', iconClassName: 'car-default' },
    { make: 'Gonow', iconClassName: 'car-default' },
    { make: 'Geely', iconClassName: 'car-default' },
    { make: 'Byton', iconClassName: 'car-default' },
    { make: 'Daihatsu', iconClassName: 'car-default' },
    { make: 'Isdera', iconClassName: 'car-default' },
    { make: 'Yugo', iconClassName: 'car-default' },
    { make: 'Autobianchi', iconClassName: 'car-default' },
    { make: 'SsangYong', iconClassName: 'car-default' },
    { make: 'Triumph', iconClassName: 'car-default' },
    { make: 'Goggomobil', iconClassName: 'car-default' },
    { make: 'Heinkel', iconClassName: 'car-default' },
    { make: 'Wartburg', iconClassName: 'car-default' },
    { make: 'Borgward', iconClassName: 'car-default' },
    { make: 'Glas', iconClassName: 'car-default' },
    { make: 'DKW', iconClassName: 'car-default' },
    { make: 'Wanderer', iconClassName: 'car-default' },
    { make: 'Horch', iconClassName: 'car-default' },
    { make: 'Borgward', iconClassName: 'car-default' },
    { make: 'Goliath', iconClassName: 'car-default' },
    { make: 'Lloyd', iconClassName: 'car-default' },
    { make: 'Hanomag', iconClassName: 'car-default' },
    { make: 'Nsu', iconClassName: 'car-default' },
    { make: 'Robur', iconClassName: 'car-default' },
    { make: 'Izh', iconClassName: 'car-default' },
    { make: 'Tatra', iconClassName: 'car-default' },
    { make: 'Skoda', iconClassName: 'car-skoda' },
    { make: 'Tatras', iconClassName: 'car-default' },
    { make: 'Rally', iconClassName: 'car-default' },
    { make: 'Rally', iconClassName: 'car-default' },
    { make: 'DKW', iconClassName: 'car-default' },
    { make: 'Wanderer', iconClassName: 'car-default' },
    { make: 'Horch', iconClassName: 'car-default' },
    { make: 'Man', iconClassName: 'car-default' },
    { make: 'Fiat', iconClassName: 'car-fiat' },
    { make: 'Alfa Romeo', iconClassName: 'car-alfa-romeo' },
    { make: 'Aston Martin', iconClassName: 'car-aston-martin' },
    { make: 'Renault', iconClassName: 'car-renault' },
    { make: 'Alpine', iconClassName: 'car-default' },
    { make: 'Peugeot', iconClassName: 'car-peugeot' },
    { make: 'Citroen', iconClassName: 'car-citroen' },
    { make: 'DS Automobiles', iconClassName: 'car-default' },
    { make: 'Simca', iconClassName: 'car-default' },
    { make: 'Panhard', iconClassName: 'car-default' },
    { make: 'Berliet', iconClassName: 'car-default' },
    { make: 'Clement-Bayard', iconClassName: 'car-default' },
    { make: 'Delage', iconClassName: 'car-default' },
    { make: 'Salmson', iconClassName: 'car-default' },
    { make: 'Ariès', iconClassName: 'car-default' },
    { make: 'Unic', iconClassName: 'car-default' },
    { make: 'Hotchkiss', iconClassName: 'car-default' },
    { make: 'Lorraine-Dietrich', iconClassName: 'car-default' },
    { make: 'Voisin', iconClassName: 'car-default' },
    { make: 'Delahaye', iconClassName: 'car-default' },
    { make: 'Talbot', iconClassName: 'car-default' },
    { make: 'Bugatti', iconClassName: 'car-bugatti' },
    { make: 'Amilcar', iconClassName: 'car-default' },
    { make: 'Salmson', iconClassName: 'car-default' },
    { make: 'Ligier', iconClassName: 'car-default' },
    { make: 'Microcar', iconClassName: 'car-default' },
    { make: 'Aixam', iconClassName: 'car-default' },
    { make: 'Casalini', iconClassName: 'car-default' },
    { make: 'Bollore', iconClassName: 'car-default' },
    { make: 'Chatenet', iconClassName: 'car-default' },
    { make: 'Ligier', iconClassName: 'car-default' },
    { make: 'Microcar', iconClassName: 'car-default' },
    { make: 'Aixam', iconClassName: 'car-default' },
    { make: 'Casalini', iconClassName: 'car-default' },
    { make: 'Bollore', iconClassName: 'car-default' },
    { make: 'Chatenet', iconClassName: 'car-default' },
];